apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    course: OPS300
spec:
  type: NodePort
  selector:
    course: OPS300
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
